export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const GET_COUNTRIES = 'GET_COUNTRIES';

export const GET_TOP_ARTICLES = 'GET_TOP_ARTICLES';
export const GET_SEARCH_ARTICLES = 'GET_SEARCH_ARTICLES';
export const GET_CATEGORY_ARTICLES = 'GET_CATEGORY_ARTICLES';
